services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "8081:8080"
    environment:
      DB_PATH: /data/hexmate.db
    volumes:
      - db:/data
    develop:
      watch:
        - path: ./server
          action: rebuild
        - path: ./client/src
          action: rebuild
        - path: ./client/public
          action: rebuild
        - path: ./client/index.html
          action: rebuild

volumes:
  db:
