/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as GameRouteImport } from './routes/game'
import { Route as CampaignIndexRouteImport } from './routes/campaign.index'
import { Route as CampaignLevelRouteImport } from './routes/campaign.$level'
import { Route as GameIndexRouteImport } from './routes/game.index'
import { Route as GameSeedRouteImport } from './routes/game.$seed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIndexRoute = CampaignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignLevelRoute = CampaignLevelRouteImport.update({
  id: '/$level',
  path: '/$level',
  getParentRoute: () => CampaignRoute,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameRoute,
} as any)
const GameSeedRoute = GameSeedRouteImport.update({
  id: '/$seed',
  path: '/$seed',
  getParentRoute: () => GameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteWithChildren
  '/custom': typeof CustomRoute
  '/game': typeof GameRouteWithChildren
  '/campaign/$level': typeof CampaignLevelRoute
  '/game/$seed': typeof GameSeedRoute
  '/campaign/': typeof CampaignIndexRoute
  '/game/': typeof GameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/campaign/$level': typeof CampaignLevelRoute
  '/game/$seed': typeof GameSeedRoute
  '/campaign': typeof CampaignIndexRoute
  '/game': typeof GameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteWithChildren
  '/custom': typeof CustomRoute
  '/game': typeof GameRouteWithChildren
  '/campaign/$level': typeof CampaignLevelRoute
  '/game/$seed': typeof GameSeedRoute
  '/campaign/': typeof CampaignIndexRoute
  '/game/': typeof GameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/custom'
    | '/game'
    | '/campaign/$level'
    | '/game/$seed'
    | '/campaign/'
    | '/game/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/custom' | '/campaign/$level' | '/game/$seed' | '/campaign' | '/game'
  id:
    | '__root__'
    | '/'
    | '/campaign'
    | '/custom'
    | '/game'
    | '/campaign/$level'
    | '/game/$seed'
    | '/campaign/'
    | '/game/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRoute: typeof CampaignRouteWithChildren
  CustomRoute: typeof CustomRoute
  GameRoute: typeof GameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/': {
      id: '/campaign/'
      path: '/'
      fullPath: '/campaign/'
      preLoaderRoute: typeof CampaignIndexRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/$level': {
      id: '/campaign/$level'
      path: '/$level'
      fullPath: '/campaign/$level'
      preLoaderRoute: typeof CampaignLevelRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/game/': {
      id: '/game/'
      path: '/'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/$seed': {
      id: '/game/$seed'
      path: '/$seed'
      fullPath: '/game/$seed'
      preLoaderRoute: typeof GameSeedRouteImport
      parentRoute: typeof GameRoute
    }
  }
}

interface CampaignRouteChildren {
  CampaignLevelRoute: typeof CampaignLevelRoute
  CampaignIndexRoute: typeof CampaignIndexRoute
}

const CampaignRouteChildren: CampaignRouteChildren = {
  CampaignLevelRoute: CampaignLevelRoute,
  CampaignIndexRoute: CampaignIndexRoute,
}

const CampaignRouteWithChildren = CampaignRoute._addFileChildren(
  CampaignRouteChildren,
)

interface GameRouteChildren {
  GameSeedRoute: typeof GameSeedRoute
  GameIndexRoute: typeof GameIndexRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameSeedRoute: GameSeedRoute,
  GameIndexRoute: GameIndexRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRoute: CampaignRouteWithChildren,
  CustomRoute: CustomRoute,
  GameRoute: GameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
